#+TITLE: THERMO MODELE D'ATMOSPHERE


L'air est considéré comme un gaz parfait en équilibre statique dans le champ de pesanteur. On s'intéresse aux évolutions de la pression $P$, de la témpérature $T$ et de la masse volumique en fonction de l'altitude $z$ du point considéré.

#+BEGIN_SRC jupyter-python
import json

with open('param.json', 'r') as openfile:
    json_object = json.load(openfile)

print(json_object)
print(type(json_object))
#+END_SRC


#+BEGIN_SRC jupyter-python  
import pandas

data = pd.read_json('param.json')
#+END_SRC


Les grandeurs $P$, $T$ et $\rho$ ne sont pas uniformes. Il faut privilégier une vision locale à une vision globale de l'atmosphère. $PV=nRT$ n'a pas vraiment de signification physique à l'échelle du volume de l'atmosphère ... et puis quel est le volume de l'atmosphère ? On va adopter une description /locale/ en utilisant un jeu de variables /intensives/ ($T$,$P$,$\rho$)

- On a la loi fondamentale de l'hydrostatique projeté sur $\vec{u_z}$ 

$$ \frac{dP}{dz} = - \rho g $$


- On réécrit l'équation d'état des G.P : 

$$ P = \frac{\rho R T }{M}$$

- Est ce qu'on connait $M$ ? On peut toujours le retrouve en l'exprimant grâce à l'équation précédente exprimée au niveau du sol : 

$$ P_0 = \frac{\rho_0 R T_0 }{M}$$

